### ISSUE TITLE
Remove skip button in specific page.

### ISSUE THREAD

**Issue by tallam85** [valnub/Framework7-Plugin-Welcomescreen#10]
Hi,
I want to remove skip button in specific slide, can anyone help on this.

**Comment by valnub** [comment]
Does this css work for you?

```css
.welcomescreen-closebtn{
  display:none;
}
```
