### ISSUE TITLE
Pagination: Bullets colour - unable to change

### ISSUE THREAD

**Issue by singhrajvirk** [valnub/Framework7-Plugin-Welcomescreen#51]
Hi, Hope someone can help me with this. I have changed the container background colour to white and fonts colour to black but I am unable to change pagination bullets colour to some thing darker. Can you please help me with some css code for bullets. 

Also any support for using dynamic bullets?

**Comment by valnub** [comment]
```css
/* Non-active bullet */
.welcomescreen-container .swiper-pagination-bullet {
  background: gray; /* if not working add !important */
}

/* Active bullet */
.welcomescreen-container .swiper-pagination-bullet-active {
  background: black; /* if not working add !important */
}
```

Not sure what you mean by dynamic bullet..
